#!/usr/bin/env python3
import os
import yaml
import sys
import subprocess
from logger import log_operation

def validate_layout():
    expected_dirs = [
        'vendor', 'resources', 'contexts', 'shared', 'dist', 'scripts', 'docs'
    ]
    missing = [d for d in expected_dirs if not os.path.isdir(d)]
    if missing:
        log_operation("validate_repo", "ERROR", f"Missing dirs: {missing}")
        print(f"CRITICAL: Missing core directories: {missing}")
        return False
    print("SUCCESS: Core directory structure is valid.")
    return True

def validate_resources():
    valid = True
    resources_root = 'resources'
    if not os.path.exists(resources_root):
        return False
    for category in os.listdir(resources_root):
        cat_path = os.path.join(resources_root, category)
        if not os.path.isdir(cat_path):
            continue
        
        for resource_id in os.listdir(cat_path):
            res_path = os.path.join(cat_path, resource_id)
            if not os.path.isdir(res_path):
                continue
            
            yaml_path = os.path.join(res_path, 'resource.yaml')
            if not os.path.exists(yaml_path):
                log_operation("validate_repo", "WARNING", f"Resource {resource_id} missing resource.yaml")
                print(f"ERROR: Resource '{resource_id}' in '{category}' is missing resource.yaml")
                valid = False
                continue
            
            try:
                with open(yaml_path, 'r') as f:
                    data = yaml.safe_load(f)
                    required_fields = ['id', 'kind', 'status', 'interfaces', 'storage', 'credentials', 'dependencies', 'dependents']
                    for field in required_fields:
                        if field not in data:
                            log_operation("validate_repo", "WARNING", f"Resource {resource_id} missing field {field}")
                            print(f"ERROR: resource.yaml for '{resource_id}' is missing required field: {field}")
                            valid = False
                    
                    # Check for STORAGE.md if defined
                    if 'storage' in data and 'contract' in data['storage']:
                        contract_path = os.path.join(res_path, data['storage']['contract'])
                        if not os.path.exists(contract_path):
                            print(f"ERROR: Storage contract '{data['storage']['contract']}' not found for '{resource_id}'")
                            valid = False
                    
                    # Check for TODOs.md
                    todos_path = os.path.join(res_path, "core/docs/TODOs.md")
                    if not os.path.exists(todos_path):
                        print(f"ERROR: TODOs.md not found for '{resource_id}'")
                        valid = False
            except Exception as e:
                log_operation("validate_repo", "ERROR", f"Failed to parse yaml for {resource_id}")
                print(f"ERROR: Failed to parse resource.yaml for '{resource_id}': {e}")
                valid = False
    
    if valid:
        print("SUCCESS: All resources validated.")
    return valid

def check_hygiene():
    suggestions = []
    
    # Check for .gitignore
    if not os.path.exists('.gitignore'):
        suggestions.append("Missing .gitignore file in root.")
    
    # Check for untracked rubbish (simple check for __pycache__ or .pyc)
    rubbish_found = False
    for root, dirs, files in os.walk('.'):
        if 'dist' in dirs: dirs.remove('dist') # skip dist
        if '.git' in dirs: dirs.remove('.git') # skip .git
        
        # Skip management and scripts cache as they are generated by this tool
        if '__pycache__' in dirs:
            if '/scripts' in root or 'repository-manager/core' in root:
                dirs.remove('__pycache__')
                continue
            rubbish_found = True
            break
        for f in files:
            if f.endswith('.pyc') or f.endswith('.pyo'):
                rubbish_found = True
                break
        if rubbish_found: break
        
    if rubbish_found:
        suggestions.append("Python cache files (__pycache__ or .pyc) found in the repository.")
        
    # Check for empty directories in resources (might be leftovers)
    resources_root = 'resources'
    if os.path.exists(resources_root):
        for category in os.listdir(resources_root):
            cat_path = os.path.join(resources_root, category)
            if os.path.isdir(cat_path) and not os.listdir(cat_path):
                suggestions.append(f"Empty resource category found: {category}")

    if suggestions:
        print("\n--- Hygiene Suggestions ---")
        for s in suggestions:
            print(f"SUGGESTION: {s}")
        log_operation("validate_repo", "INFO", f"Hygiene suggestions: {len(suggestions)}")
    else:
        print("\nSUCCESS: Repository hygiene is good.")
        
    return True

def main():
    print("--- Validating Agentic Resources Repository ---")
    layout_ok = validate_layout()
    resources_ok = validate_resources()
    check_hygiene()
    
    if layout_ok and resources_ok:
        log_operation("validate_repo", "SUCCESS", "Full validation passed")
    else:
        log_operation("validate_repo", "FAILURE", "Validation failed")
    
    if not (layout_ok and resources_ok):
        sys.exit(1)
    print("\n--- Validation Complete ---")

if __name__ == "__main__":
    main()
